repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: detect-aws-credentials
    -   id: detect-private-key
-   repo: https://github.com/getoutreach/sanctify
    sha: f16b0b2a560fe87f5ad5503da561a47be76f8956
    hooks:
    -   id: sanctify
