test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: dw_test
  pool: 5
  username: dw
  password: 'toOlY7oLVFCOL4XudzmJ'
  host: 127.0.0.1

test_mysql:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dw_test
  pool: 5
  username: dw
  password: 'toOlY7oLVFCOL4XudzmJ'
  host: 127.0.0.1

dev:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: dw_dev
  pool: 5
  username: dw
  password: 'toOlY7oLVFCOL4XudzmJ'
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: dw
  pool: 5
  username: dw
  password: 'toOlY7oLVFCOL4XudzmJ'
  host: 127.0.0.1
